apiVersion : v1
kind: Service
metadata:
  name: imafidonnodemongodockerdev 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imafidonnodemongodockerdev
  template:
    metadata:
      labels:
        app: imafidonnodemongodockerdev 
    spec:
      containers:
        - name: imafidonnodemongodockerdev 
          image: sylvester1.azurecr.io/imafidonnodemongodockerdev
          ports:
          - containerPort: 8080
